# Generated by Django 5.1.1 on 2024-09-23 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BottleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(choices=[('request', 'Request'), ('response', 'Response')], max_length=100)),
                ('point', models.IntegerField()),
                ('distance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reader', to='userapp.player')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='userapp.player')),
                ('bottle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bottles.bottleitem')),
            ],
        ),
    ]
