# Generated by Django 5.1.1 on 2024-09-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottleitem',
            name='max_characters',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='bottleitem',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
