# Generated by Django 5.1.1 on 2024-09-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottles', '0003_alter_bottleitem_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bottle',
            old_name='bottle',
            new_name='bottle_type',
        ),
        migrations.RenameField(
            model_name='bottleitem',
            old_name='point',
            new_name='points',
        ),
        migrations.RemoveField(
            model_name='bottleitem',
            name='text',
        ),
        migrations.AddField(
            model_name='bottle',
            name='response',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='bottle',
            name='text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
