# Generated by Django 5.1.1 on 2024-09-25 08:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_text_read',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='player',
            name='response',
            field=models.BooleanField(default=False),
        ),
    ]
