# Generated by Django 5.1.1 on 2024-09-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_player_last_text_read_player_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_text_read',
            field=models.DateField(),
        ),
    ]
