# Generated by Django 5.1.1 on 2024-09-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_player_last_text_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='all_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
